# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hailong11/Documents/src/github.com/hailongz/kk-object

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hailong11/Documents/src/github.com/hailongz/kk-object

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hailong11/Documents/src/github.com/hailongz/kk-object/CMakeFiles /Users/hailong11/Documents/src/github.com/hailongz/kk-object/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hailong11/Documents/src/github.com/hailongz/kk-object/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kk-object

# Build rule for target.
kk-object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kk-object
.PHONY : kk-object

# fast build rule for target.
kk-object/fast:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/build
.PHONY : kk-object/fast

lib/md5/md5.o: lib/md5/md5.c.o

.PHONY : lib/md5/md5.o

# target to build an object file
lib/md5/md5.c.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/lib/md5/md5.c.o
.PHONY : lib/md5/md5.c.o

lib/md5/md5.i: lib/md5/md5.c.i

.PHONY : lib/md5/md5.i

# target to preprocess a source file
lib/md5/md5.c.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/lib/md5/md5.c.i
.PHONY : lib/md5/md5.c.i

lib/md5/md5.s: lib/md5/md5.c.s

.PHONY : lib/md5/md5.s

# target to generate assembly for a file
lib/md5/md5.c.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/lib/md5/md5.c.s
.PHONY : lib/md5/md5.c.s

src/kk-atomic-pthread.o: src/kk-atomic-pthread.cc.o

.PHONY : src/kk-atomic-pthread.o

# target to build an object file
src/kk-atomic-pthread.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-atomic-pthread.cc.o
.PHONY : src/kk-atomic-pthread.cc.o

src/kk-atomic-pthread.i: src/kk-atomic-pthread.cc.i

.PHONY : src/kk-atomic-pthread.i

# target to preprocess a source file
src/kk-atomic-pthread.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-atomic-pthread.cc.i
.PHONY : src/kk-atomic-pthread.cc.i

src/kk-atomic-pthread.s: src/kk-atomic-pthread.cc.s

.PHONY : src/kk-atomic-pthread.s

# target to generate assembly for a file
src/kk-atomic-pthread.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-atomic-pthread.cc.s
.PHONY : src/kk-atomic-pthread.cc.s

src/kk-binary.o: src/kk-binary.cc.o

.PHONY : src/kk-binary.o

# target to build an object file
src/kk-binary.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-binary.cc.o
.PHONY : src/kk-binary.cc.o

src/kk-binary.i: src/kk-binary.cc.i

.PHONY : src/kk-binary.i

# target to preprocess a source file
src/kk-binary.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-binary.cc.i
.PHONY : src/kk-binary.cc.i

src/kk-binary.s: src/kk-binary.cc.s

.PHONY : src/kk-binary.s

# target to generate assembly for a file
src/kk-binary.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-binary.cc.s
.PHONY : src/kk-binary.cc.s

src/kk-bio.o: src/kk-bio.cc.o

.PHONY : src/kk-bio.o

# target to build an object file
src/kk-bio.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-bio.cc.o
.PHONY : src/kk-bio.cc.o

src/kk-bio.i: src/kk-bio.cc.i

.PHONY : src/kk-bio.i

# target to preprocess a source file
src/kk-bio.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-bio.cc.i
.PHONY : src/kk-bio.cc.i

src/kk-bio.s: src/kk-bio.cc.s

.PHONY : src/kk-bio.s

# target to generate assembly for a file
src/kk-bio.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-bio.cc.s
.PHONY : src/kk-bio.cc.s

src/kk-block.o: src/kk-block.cc.o

.PHONY : src/kk-block.o

# target to build an object file
src/kk-block.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-block.cc.o
.PHONY : src/kk-block.cc.o

src/kk-block.i: src/kk-block.cc.i

.PHONY : src/kk-block.i

# target to preprocess a source file
src/kk-block.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-block.cc.i
.PHONY : src/kk-block.cc.i

src/kk-block.s: src/kk-block.cc.s

.PHONY : src/kk-block.s

# target to generate assembly for a file
src/kk-block.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-block.cc.s
.PHONY : src/kk-block.cc.s

src/kk-chan.o: src/kk-chan.cc.o

.PHONY : src/kk-chan.o

# target to build an object file
src/kk-chan.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-chan.cc.o
.PHONY : src/kk-chan.cc.o

src/kk-chan.i: src/kk-chan.cc.i

.PHONY : src/kk-chan.i

# target to preprocess a source file
src/kk-chan.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-chan.cc.i
.PHONY : src/kk-chan.cc.i

src/kk-chan.s: src/kk-chan.cc.s

.PHONY : src/kk-chan.s

# target to generate assembly for a file
src/kk-chan.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-chan.cc.s
.PHONY : src/kk-chan.cc.s

src/kk-crypto.o: src/kk-crypto.cc.o

.PHONY : src/kk-crypto.o

# target to build an object file
src/kk-crypto.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-crypto.cc.o
.PHONY : src/kk-crypto.cc.o

src/kk-crypto.i: src/kk-crypto.cc.i

.PHONY : src/kk-crypto.i

# target to preprocess a source file
src/kk-crypto.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-crypto.cc.i
.PHONY : src/kk-crypto.cc.i

src/kk-crypto.s: src/kk-crypto.cc.s

.PHONY : src/kk-crypto.s

# target to generate assembly for a file
src/kk-crypto.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-crypto.cc.s
.PHONY : src/kk-crypto.cc.s

src/kk-dispatch.o: src/kk-dispatch.cc.o

.PHONY : src/kk-dispatch.o

# target to build an object file
src/kk-dispatch.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-dispatch.cc.o
.PHONY : src/kk-dispatch.cc.o

src/kk-dispatch.i: src/kk-dispatch.cc.i

.PHONY : src/kk-dispatch.i

# target to preprocess a source file
src/kk-dispatch.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-dispatch.cc.i
.PHONY : src/kk-dispatch.cc.i

src/kk-dispatch.s: src/kk-dispatch.cc.s

.PHONY : src/kk-dispatch.s

# target to generate assembly for a file
src/kk-dispatch.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-dispatch.cc.s
.PHONY : src/kk-dispatch.cc.s

src/kk-ev.o: src/kk-ev.cc.o

.PHONY : src/kk-ev.o

# target to build an object file
src/kk-ev.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ev.cc.o
.PHONY : src/kk-ev.cc.o

src/kk-ev.i: src/kk-ev.cc.i

.PHONY : src/kk-ev.i

# target to preprocess a source file
src/kk-ev.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ev.cc.i
.PHONY : src/kk-ev.cc.i

src/kk-ev.s: src/kk-ev.cc.s

.PHONY : src/kk-ev.s

# target to generate assembly for a file
src/kk-ev.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ev.cc.s
.PHONY : src/kk-ev.cc.s

src/kk-event.o: src/kk-event.cc.o

.PHONY : src/kk-event.o

# target to build an object file
src/kk-event.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-event.cc.o
.PHONY : src/kk-event.cc.o

src/kk-event.i: src/kk-event.cc.i

.PHONY : src/kk-event.i

# target to preprocess a source file
src/kk-event.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-event.cc.i
.PHONY : src/kk-event.cc.i

src/kk-event.s: src/kk-event.cc.s

.PHONY : src/kk-event.s

# target to generate assembly for a file
src/kk-event.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-event.cc.s
.PHONY : src/kk-event.cc.s

src/kk-http.o: src/kk-http.cc.o

.PHONY : src/kk-http.o

# target to build an object file
src/kk-http.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-http.cc.o
.PHONY : src/kk-http.cc.o

src/kk-http.i: src/kk-http.cc.i

.PHONY : src/kk-http.i

# target to preprocess a source file
src/kk-http.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-http.cc.i
.PHONY : src/kk-http.cc.i

src/kk-http.s: src/kk-http.cc.s

.PHONY : src/kk-http.s

# target to generate assembly for a file
src/kk-http.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-http.cc.s
.PHONY : src/kk-http.cc.s

src/kk-object.o: src/kk-object.cc.o

.PHONY : src/kk-object.o

# target to build an object file
src/kk-object.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-object.cc.o
.PHONY : src/kk-object.cc.o

src/kk-object.i: src/kk-object.cc.i

.PHONY : src/kk-object.i

# target to preprocess a source file
src/kk-object.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-object.cc.i
.PHONY : src/kk-object.cc.i

src/kk-object.s: src/kk-object.cc.s

.PHONY : src/kk-object.s

# target to generate assembly for a file
src/kk-object.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-object.cc.s
.PHONY : src/kk-object.cc.s

src/kk-script.o: src/kk-script.cc.o

.PHONY : src/kk-script.o

# target to build an object file
src/kk-script.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-script.cc.o
.PHONY : src/kk-script.cc.o

src/kk-script.i: src/kk-script.cc.i

.PHONY : src/kk-script.i

# target to preprocess a source file
src/kk-script.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-script.cc.i
.PHONY : src/kk-script.cc.i

src/kk-script.s: src/kk-script.cc.s

.PHONY : src/kk-script.s

# target to generate assembly for a file
src/kk-script.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-script.cc.s
.PHONY : src/kk-script.cc.s

src/kk-string.o: src/kk-string.cc.o

.PHONY : src/kk-string.o

# target to build an object file
src/kk-string.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-string.cc.o
.PHONY : src/kk-string.cc.o

src/kk-string.i: src/kk-string.cc.i

.PHONY : src/kk-string.i

# target to preprocess a source file
src/kk-string.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-string.cc.i
.PHONY : src/kk-string.cc.i

src/kk-string.s: src/kk-string.cc.s

.PHONY : src/kk-string.s

# target to generate assembly for a file
src/kk-string.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-string.cc.s
.PHONY : src/kk-string.cc.s

src/kk-wk.o: src/kk-wk.cc.o

.PHONY : src/kk-wk.o

# target to build an object file
src/kk-wk.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-wk.cc.o
.PHONY : src/kk-wk.cc.o

src/kk-wk.i: src/kk-wk.cc.i

.PHONY : src/kk-wk.i

# target to preprocess a source file
src/kk-wk.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-wk.cc.i
.PHONY : src/kk-wk.cc.i

src/kk-wk.s: src/kk-wk.cc.s

.PHONY : src/kk-wk.s

# target to generate assembly for a file
src/kk-wk.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-wk.cc.s
.PHONY : src/kk-wk.cc.s

src/kk-ws.o: src/kk-ws.cc.o

.PHONY : src/kk-ws.o

# target to build an object file
src/kk-ws.cc.o:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ws.cc.o
.PHONY : src/kk-ws.cc.o

src/kk-ws.i: src/kk-ws.cc.i

.PHONY : src/kk-ws.i

# target to preprocess a source file
src/kk-ws.cc.i:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ws.cc.i
.PHONY : src/kk-ws.cc.i

src/kk-ws.s: src/kk-ws.cc.s

.PHONY : src/kk-ws.s

# target to generate assembly for a file
src/kk-ws.cc.s:
	$(MAKE) -f CMakeFiles/kk-object.dir/build.make CMakeFiles/kk-object.dir/src/kk-ws.cc.s
.PHONY : src/kk-ws.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kk-object"
	@echo "... lib/md5/md5.o"
	@echo "... lib/md5/md5.i"
	@echo "... lib/md5/md5.s"
	@echo "... src/kk-atomic-pthread.o"
	@echo "... src/kk-atomic-pthread.i"
	@echo "... src/kk-atomic-pthread.s"
	@echo "... src/kk-binary.o"
	@echo "... src/kk-binary.i"
	@echo "... src/kk-binary.s"
	@echo "... src/kk-bio.o"
	@echo "... src/kk-bio.i"
	@echo "... src/kk-bio.s"
	@echo "... src/kk-block.o"
	@echo "... src/kk-block.i"
	@echo "... src/kk-block.s"
	@echo "... src/kk-chan.o"
	@echo "... src/kk-chan.i"
	@echo "... src/kk-chan.s"
	@echo "... src/kk-crypto.o"
	@echo "... src/kk-crypto.i"
	@echo "... src/kk-crypto.s"
	@echo "... src/kk-dispatch.o"
	@echo "... src/kk-dispatch.i"
	@echo "... src/kk-dispatch.s"
	@echo "... src/kk-ev.o"
	@echo "... src/kk-ev.i"
	@echo "... src/kk-ev.s"
	@echo "... src/kk-event.o"
	@echo "... src/kk-event.i"
	@echo "... src/kk-event.s"
	@echo "... src/kk-http.o"
	@echo "... src/kk-http.i"
	@echo "... src/kk-http.s"
	@echo "... src/kk-object.o"
	@echo "... src/kk-object.i"
	@echo "... src/kk-object.s"
	@echo "... src/kk-script.o"
	@echo "... src/kk-script.i"
	@echo "... src/kk-script.s"
	@echo "... src/kk-string.o"
	@echo "... src/kk-string.i"
	@echo "... src/kk-string.s"
	@echo "... src/kk-wk.o"
	@echo "... src/kk-wk.i"
	@echo "... src/kk-wk.s"
	@echo "... src/kk-ws.o"
	@echo "... src/kk-ws.i"
	@echo "... src/kk-ws.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

